### ISSUE TITLE
Thread for current project

### ISSUE THREAD

**Issue by JKerb** [Java2Class/minigolf#1]
Above.  Not really sure what I'm doing.  Anyone know how to create the program for testing?  He is not very specific with what he wants his classes to look like.  I'm pretty much stuck trying to figure out what he wants.

**Comment by scrizz** [comment]
I've got some finals today and tomorrow.
I'll put more after exams tomorrow.

Everyone is welcome to push some code

**Comment by JSilvey** [comment]
Okay, I have added all of the skeleton code and classes that he wanted. Now we need to write tests for the classes. As he said the tests are not expected to be passed since the code is all skeleton code and does nothing. We need to decide on a file format to store our data records in. I vote just a plain text file but what ever we decide we need to make sure it is specified and included in the submission.  So I guess for right now we need to write JUNIT tests. 

We are also supposed to decide which part of the project we are testing either the Round or (Course and Main classes). I vote we test the Round class

**Comment by JKerb** [comment]
I have made tests for the Round class.  Let me push it

**Comment by JSilvey** [comment]
Looks good. I will work on the enterScore tests

**Comment by JKerb** [comment]
I made a data record (text file) but I'm not sure where to implement it.  Are we supposed to load it in the Course class?  From what I see it's supposed to contain the name of the golf course, the address, each hole, and the par for each hole.

**Comment by JSHaven** [comment]
It's not perfect, I made a few mistakes, but it's a start. also...
(Quoted from wpollock.com's mini golf assignment)
"
 Team Assignments:

One team will test class Round and any additional methods or foundational classes needed.

One team will test class Course and class Main, and add any additional methods or foundational classes needed.

(Your team can pick either part of the design to test.  Just let the instructor know once you have decided.)
"
So I assume we are just doing Round.

**Comment by JKerb** [comment]
Yeah doing Round is fine.  You need the damn Rosetta Stone to read this.

**Comment by JSHaven** [comment]
From what I got, DO NOT USE each other's stuff. I mean it's all supposed to be independent. Like if you see for my example 3: I could use "get" or call a method, but I used random numbers. Also, if you read the Round class...

(Quoted from wpollock.com)
"
 Class Round holds a player's information for the current round of golf: their name, the course name, and the number of strokes per hole (for each hole played so far).  An object of this class is created when a customer pays for a round and their name is entered by the operator, which also creates a swipe-card.

The round information is not stored beyond the closing time of any course (or, say “midnight” for 24 hour courses if any).  This means that unlike the “course” data, you don't need to persist round data to storage.  However when running low on RAM the garbage collector should be able to reclaim Round objects that have been completed. 
"
I missed that before, so I mean guess you HAVE to call on class Round since that is what you're testing, but we're supposed to leave Main and Course out. (like I don't think you're supposed to call Course to get info. Instead, you make up a number or something).

I'm still piecing it together so, HOPEFULLY you kinda have an idea @_@;

**Comment by JSHaven** [comment]
Yeah, it's confusing... I know ~_~

**Comment by JSilvey** [comment]
What do you mean by DO NOT USE each others stuff. Where are you talking about?

**Comment by JSHaven** [comment]
Also, I'm just guessing what I'm doing here based on his examples in the project description and his notes, so I'm not 100% I'm doing this right, but it's what I was working on yesterday in class. I believe Example 3 is closer to being right since there is four tests (1 for good input, 3 for bad inputs with different examples).

**Comment by JSHaven** [comment]
We're not implementing each others work. Like I don't think you're supposed to use my code to solve your code. I believe the point for now is we all have to be standalone, then when it wokrs wee call and implement each other. Like instead of :+1: 
i = Round.getScore() ;                   that calls Silvey's code I have to just make up a number
i = 5;                                              and test that to see if my code works. Then when it does I call Silvey, but I don't think we'll get that far since we are just testing.

**Comment by JSHaven** [comment]
I think we all HAVE to call the base Round class, but I believe we can't call on each other. I could be wrong here, but that's the impression I got in his examples.

**Comment by JSHaven** [comment]
(The base round class is:  Class Round holds a player's information for the current round of golf: their name, the course name, and the number of strokes per hole (for each hole played so far).  An object of this class is created when a customer pays for a round and their name is entered by the operator, which also creates a swipe-card.

The round information is not stored beyond the closing time of any course (or, say “midnight” for 24 hour courses if any).  This means that unlike the “course” data, you don't need to persist round data to storage.  However when running low on RAM the garbage collector should be able to reclaim Round objects that have been completed. )

**Comment by JSilvey** [comment]
I'm confused. I'll just go with it. :+1:

**Comment by JSHaven** [comment]
I'm confused too... sorry ~_~

**Comment by JKerb** [comment]
Same here.  If you feel something is wrong about mine, feel free to modify it, lol.

**Comment by JSHaven** [comment]
What I'm trying to say is this:
FAKE EXAMPLE:
If Kerby has the method getPersonsName( ); and I have a method where I have to display a person's name like DisplayGameResults( ). Since Kerby is still testing getPersonsName, it would make my method impossible to do without his. So, I would NOT call Kerby's Method and create a fake name just to see if my method works. Once Kerby get's his method working and I know mine works, THEN I call his method. 

For the project we're not going as far as finishing this project so we will NEVER get to the point of calling each other's methods. From what I got we were just seeing if our methods work independently. Like I need to see if my method DisplayGameResults( ) works without calling Kerby's method GetPersonsName( ) just to see if I did MY method correctly. So, I creating a fake name just to test my method.

**Comment by JSilvey** [comment]
Okay I see what you are saying now. You are correct. We are just testing each method independently. 
I copied what you did on the old project page and posted it in another issue on this page so we can keep everything together.

**Comment by JSHaven** [comment]
So, we are all testing class Round and the only definite things we know working in class Round is: their name, the course name, and the number of strokes per hole (for each hole played so far). So, you can call Round.PersonsName( ) or Round.CourseName( ), but you CANNOT call Round.currentScores( ) since I'm still making that part. So you can call what's given, but you can't call what we are testing since it's not working yet.

**Comment by JSHaven** [comment]
My earlier code was partly wrong cause I missed that chunk of info I told you (just found out myself). But yeah this project was not explained clearly lol

**Comment by JSilvey** [comment]
Make sure you are coding your test cases into program. Kerby already has a TestClass  class in the minigolf package. Just put your code in it.

**Comment by JSHaven** [comment]
Also, back to my earlier statement, even when I am done with Round.currentScore ( ) you still cannot call it because the idea is it's independent so don't plan on using Round.currentScores for your part (no offense it's just what the project asks for). if you need to call Round.currentScore, don't and make up a random number instead. and Okay lol

**Comment by JSHaven** [comment]
Well, Kerby, if you are doing the class, The only things you need is to create a Person Name, The Course Name, and the strokes per hole ( Up to the hole we are in). Since Kerby is doing the class, he's the only person we can call since he's the test material. We all good? We all get it a bit better? lol

**Comment by JSHaven** [comment]
strokes per hole I would assume is an array and I don't think it'll hurt if you do a complete set. For example. We can just say for simple measure there are only 5 holes all together or something.

**Comment by JSHaven** [comment]
Well, here's my updated test. The only thing I need to do is change the "r.strokesPerHole[ ]()" to whatever Kerby named it.

import org.junit._; // The various annotations 
import static org.junit.Assert._; //AssertX methods 
import org.junit.runner.JUnitCore; // Test runner

//Test to check to see if graded score has a value.

public class MyTestSuite
{   

```
//sets up items used
private Round r ;
private currentHoleNum ;
private int [ ] parAvg ; 
private int [ ] currentScore ;
private int [ ] gradedScore ;
private int [ ] badParAvg ;
private int [ ] badCurrentScore1 ;
private int [ ] badCurrentScore2 ;

@Before
public void init ()
{
    //Declare the values of the items used.
    Round r = new Round ( ) ; 
    currentHoleNum = 3;
    int [ ] parAvg = { 3 , 4 , 3 , 5 , 2 } ; 
    int [ ] currentScore = r.strokesPerHole[]();
    int [ ] gradedScore = new int [ currentHoleNum - 1 ] ;
    int [ ] badParAvg = { 5 , 0 , 0 ,  , 7 } ;
    int [ ] badCurrentScore1 = { 2 ,   , 5 , 6 , 3 } ;
    int [ ] badCurrentScore2 = { 2 , 3 , 5 , 6 } ;

    /Test 1
@Test
public void testCurrentScoreValueGood( )
{
    //Temp Variable
    int i = 0;

    //Calculating graded score
    for (  i = 0 ; i < currentHoleNum ; i ++ )
    {
        //Calculate grade ( 2 is over the par, -2 is below it. For example,
        //If the par is 5 (means it takes the average person 5 swings to
        //get the ball in the hole, so 2 means it took you 7 swings and
        //-2 means it took you 3 swings.
        gradedScore[ i ] = currentScore[ i ] - parAvg[ i ] ;

        //Brings up a warning if the value is null.
        assertNull ( gradedScore[ i ] ) ;
        //Bring up a warning statement is currentScore[ ] is the same as gradedScore[ ].
        assertArrayEquals ( currentScore, gradedScore ) ;
        //Brings up a warning if parAvg[ ] is the same as gradedScore[ ].
        assertArrayEquals ( parAvg, gradedScore ) ; 
        //

    }
}

    //Test 2
@Test
public void testCurrentScoreValueBad1( )
{
    //Temp Variable
    int i = 0;

    //Calculating graded score
    for (  i = 0 ; i < currentHoleNum ; i ++ )
    {
        //Calculate grade ( 2 is over the par, -2 is below it. For example,
        //If the par is 5 (means it takes the average person 5 swings to
        //get the ball in the hole, so 2 means it took you 7 swings and
        //-2 means it took you 3 swings.
        gradedScore[ i ] = currentScore[ i ] - badParAvg[ i ] ;

        //Brings up a warning if the value is null.
        assertNull ( gradedScore[ i ] ) ;
        //Bring up a warning statement is currentScore[ ] is the same as gradedScore[ ].
        assertArrayEquals ( currentScore, gradedScore ) ;
        //Brings up a warning if parAvg[ ] is the same as gradedScore[ ].
        assertArrayEquals ( badParAvg, gradedScore ) ; 

    }
}

    //Test 3
@Test
public void testCurrentScoreValueBad2( )
{
    //Temp Variable
    int i = 0;

    //Calculating graded score
    for (  i = 0 ; i < currentHoleNum ; i ++ )
    {
        //Calculate grade ( 2 is over the par, -2 is below it. For example,
        //If the par is 5 (means it takes the average person 5 swings to
        //get the ball in the hole, so 2 means it took you 7 swings and
        //-2 means it took you 3 swings.
        gradedScore[ i ] = badCurrentScore1[ i ] - parAvg[ i ] ;

        //Brings up a warning if the value is null.
        assertNull ( gradedScore[ i ] ) ;
        //Bring up a warning statement is currentScore[ ] is the same as gradedScore[ ].
        assertArrayEquals ( badCurrentScore1, gradedScore ) ;
        //Brings up a warning if parAvg[ ] is the same as gradedScore[ ].
        assertArrayEquals ( parAvg, gradedScore ) ; 

    }
}

    //Test 4
@Test
public void testCurrentScoreValueBad3( )
{
    //Temp Variable
    int i = 0;

    //Calculating graded score
    for (  i = 0 ; i < currentHoleNum ; i ++ )
    {
        //Calculate grade ( 2 is over the par, -2 is below it. For example,
        //If the par is 5 (means it takes the average person 5 swings to
        //get the ball in the hole, so 2 means it took you 7 swings and
        //-2 means it took you 3 swings.
        gradedScore[ i ] = badCurrentScore2[ i ] - parAvg[ i ] ;

        //Brings up a warning if the value is null.
        assertNull ( gradedScore[ i ] ) ;
        //Bring up a warning statement is currentScore[ ] is the same as gradedScore[ ].
        assertArrayEquals ( badCurrentScore2, gradedScore ) ;
        //Brings up a warning if parAvg[ ] is the same as gradedScore[ ].
        assertArrayEquals ( parAvg, gradedScore ) ; 
    }
}
```

}

**Comment by JSHaven** [comment]
Okay, I'm SSOOOOOOOO sorry for all of that. This damn project is SOOOOO confusing. Here, this should work now. But In order for it to work, you MUST download JUnit. It will not work by itself.

//@author Haven Brewer

package minigolf;
import minigolf.Round;
import org.junit._; // The various annotations
import static org.junit.Assert._; //AssertX methods

//Test to check to see if graded score has a value.

public class MyTestSuite
{

```
//sets up items used
private Round r ;
private int currentHoleNum ;

//The player's scores for a full game
//(I'm not sure how to read from a file through, sorry)
private int [ ] parScore = { 2 , 3 , 5 , 2 , 4 , 3 , 1 , 2 , 4 , 5 , 2 , 3 , 4 ,
    5 , 2 , 1 , 3 , 4 } ;

//Overall Score
private int currentScore ;

@Before
public void init ()
{
    //Declare the values of the items used.
    r = new Round ( ) ; 
    currentHoleNum = 6 ;
    currentScore = 0 ;

    int i = currentHoleNum - 1 ; 
}

//Test 
@Test
public int testCurrentScoreValue( )
{
    //Calculating graded score
    for (  int i = 0 ; i < currentHoleNum ; i ++ )
    {
        currentScore = currentScore + parScore [ i ] ;
        assertFalse ("higher than current Hole value", i > currentHoleNum ) ;
    }

    assertNull (currentScore); 

    return currentScore;
} 
```

}

again, sorry for all the confusion ~_~

**Comment by scrizz** [comment]
Ok, finished with 3 of my exams(3 more to go lol). 
I want to apologize for not being more involved with this project.
This project came up at a really bad time.
What's left in this project that I can do?

**Comment by JSHaven** [comment]
crap, I messed up, sorry Man, so faking confusing. Am I doing the overall player's score or the player's score compared to the Par? O_o;

**Comment by JSHaven** [comment]
Really just methods like:

 int numberOfHolesPlayed ()
Returns the number of completed holes in this round;

void enterScore(int strokes)
Enter a score for the next hole.  (Note the current design doesn't allow a player to skip holes, they must be played in order); 

take a pick and go for it lol.

**Comment by JSHaven** [comment]
For now, I just added the player's score. am I doing like a positive or negaitive number based on the Par's average score or am I doing just the player's score?

**Comment by JSHaven** [comment]
Ok I'm signing out for the night. If you need me, text me. Have a good night! XD

**Comment by scrizz** [comment]
w8. where am I supposed to add stuff?  I see methods with the same name all over the place.

**Comment by JSilvey** [comment]
Some methods are duplicates per his instructions. All the skeleton methods of the main code are there. We just need to get the test code class written. I have to research more on test classes because I have no idea what to write. I'll look at it more later tonight. I was going to try and do the test methods enterScoreLegal and illegal but if you need something to do feel free to take that over. Otherwise I'll figure it out tonight.

**Comment by scrizz** [comment]
Thanks

**Comment by scrizz** [comment]
ok I added the number of holes played test method.
let me know if it is right.

**Comment by JSilvey** [comment]
I'm so confused. Do we even need to test the enterScore method since it doesn't return a value? I can't figure out what to write as a test.

**Comment by JKerb** [comment]
I think so, you just send it positive or negative or whatever scores, even though it won't do anything with them.  I think.  Because he hasn't specified anything inside of the method, it's just too ridiculous.

**Comment by JSilvey** [comment]
okay I pushed tests for the method. i have no idea if they are right or not but they are there. I'm calling it a night. it looks like we are about done right?

**Comment by JSHaven** [comment]
Enter score (I would assume) adds an object to the array, so it doesn't return anything because you would modify an array, which I don't think get's past like normal ints. It's more like an object and you don't past objects... but then again I've been drink so XD

**Comment by JKerb** [comment]
I'd say so man.. we did a lot of stuff.  I think it's good enough.  I'll submit tomorrow at the normal time.

**Comment by JSHaven** [comment]
COOL I like the sound of that XD

**Comment by scrizz** [comment]
ok. GJ guys. give yourselves a pat on the back lol

**Comment by JSHaven** [comment]
sorry, I can't reach it @_@

**Comment by scrizz** [comment]
......... That's what she said........

srry, I had to. lol
(I'll walk myself out)
